export default {
  wran: "icon-jinggao",
  blog: "icon-blog",
  toTop: "icon-huidaodingbu",
  code: "icon-QA",
  project: "icon-code",
  close: "icon-guanbi",

  zhenque: "icon-zhengque",
  email: "icon-email",
  empty: "icon-empty1",
  message: "icon-fl-xinxi",
  home: "icon-zhuye1",
  arrowUp: "icon-shangjiantou",
  qq: "icon-logo-qq",
  arrowDown: "icon-jiantou9",
  liuyan: "icon-liuyan",
  github: "icon-github1",
  about: "icon-set_about_hov",
  weixin: "icon-weixin",
};
